# Generated by Django 3.1.1 on 2020-10-04 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_master',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
