# Generated by Django 3.1.1 on 2020-10-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201004_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior')], default='J', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
