# Generated by Django 3.1.1 on 2020-10-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201005_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior'), ('N', 'No level')], default='N', max_length=1),
        ),
    ]
