# Generated by Django 3.1.1 on 2020-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201017_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
