# Generated by Django 3.1.1 on 2020-10-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
