# Generated by Django 3.1.1 on 2020-10-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
    ]
