# Generated by Django 3.1.1 on 2020-10-04 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'planed'), ('D', 'done'), ('C', 'canceled')], default='P', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.procedures')),
            ],
        ),
        migrations.CreateModel(
            name='master_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField()),
                ('text', models.TextField(default=' ')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.works')),
            ],
        ),
    ]
