# Generated by Django 3.1.1 on 2020-10-04 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_master_comments_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(default=5)),
                ('text', models.TextField(default=' ')),
            ],
        ),
        migrations.RemoveField(
            model_name='masters',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='nic_name',
        ),
        migrations.AddField(
            model_name='masters',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masters',
            name='rank',
            field=models.CharField(choices=[('J', 'Junior'), ('M', 'Middle'), ('S', 'Senior')], default='J', max_length=1),
        ),
        migrations.AddField(
            model_name='works',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.masters'),
        ),
        migrations.DeleteModel(
            name='master_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.works'),
        ),
    ]
