# Generated by Django 3.1.1 on 2020-10-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201004_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masters',
            old_name='rank',
            new_name='level',
        ),
    ]
