# Generated by Django 3.1.1 on 2020-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201005_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='mark',
        ),
        migrations.AddField(
            model_name='comments',
            name='rate',
            field=models.SmallIntegerField(choices=[(5, 'Excelent'), (4, 'Good'), (3, 'Not bad'), (2, 'Bad'), (1, 'Horribly')], default=5),
        ),
    ]
