# Generated by Django 3.1.1 on 2020-10-05 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0012_auto_20201005_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_client', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='works',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='works',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
