# Generated by Django 3.1.1 on 2020-10-05 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201005_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='insert_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 5, 15, 19, 49, 40102, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
