# Generated by Django 3.1.1 on 2020-10-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_comments_insert_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='masters',
        ),
    ]
