# Generated by Django 3.1.1 on 2020-10-07 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_delete_masters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='works',
            new_name='Orders',
        ),
    ]
