# Generated by Django 3.1.1 on 2020-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201013_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rate',
            field=models.SmallIntegerField(choices=[(5, 'Excelent'), (4, 'Good'), (3, 'Not bad'), (2, 'Bad'), (1, 'Horribly'), (0, 'Not rated')], default=0),
        ),
    ]
