# Generated by Django 3.1.1 on 2020-11-02 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_masterprocedure'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterprocedure',
            unique_together={('master', 'procedure')},
        ),
    ]
